### ISSUE TITLE
ScalaJS artifact for ScalaJS 1.x was compiled with ScalaJS 0.6.29

### ISSUE THREAD

**Issue by swachter** [endpoints4s/endpoints4s#604]
I try to use endpoint4s in a ScalaJS project. The endpoint4s artifact that should be compiled for ScalaJS 1.x was compiled with ScalaJS 0.6.29. The following exception is raised:

```
[error] java.io.IOException: Failed to deserialize /home/swachter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/endpoints4s/algebra-json-schema_sjs1_2.13/1.0.0/algebra-json-schema_sjs1_2.13-1.0.0.jar:/endpoints/algebra/Decoder$$$Lambda$1.sjsir
[error]         at org.scalajs.linker.interface.unstable.IRFileImpl$$anonfun$withPathExceptionContext$1.applyOrElse(IRFileImpl.scala:65)
[error]         at org.scalajs.linker.interface.unstable.IRFileImpl$$anonfun$withPathExceptionContext$1.applyOrElse(IRFileImpl.scala:58)
[error]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
...
[error] Caused by: java.lang.IllegalArgumentException: malformed version: 0.6.29
[error]     at org.scalajs.ir.VersionChecks$.$anonfun$mustMatch$1(ScalaJSVersions.scala:99)
[error]     at scala.Option.getOrElse(Option.scala:189)
[error]     at org.scalajs.ir.VersionChecks$.mustMatch(ScalaJSVersions.scala:99)```

**Comment by julienrf** [comment]
Thanks for reporting. Indeed, the artifact does contain some stale compilation products that were compiled with 0.6.29.

Can you try to use the version number `1.0.0-sjs1` for Scala.js artifacts?

~~~
libraryDependencies += "org.endpoints4s" %%% "xhr-client" % "1.0.0+sjs1"
~~~

**Comment by lolgab** [comment]
I think it's worth linking: https://gitter.im/scala-js/scala-js?at=5f08f39564ef9d04b2a69d1f

**Comment by swachter** [comment]
appending the suffix `+sjs1` helped

**Comment by julienrf** [comment]
Thank you for your feedback. I’m closing the issue.
